//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DiseaseList> DiseaseList { get; set; }
        public virtual DbSet<DiseaseStatus> DiseaseStatus { get; set; }
        public virtual DbSet<DiseaseVisit> DiseaseVisit { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<MedCard> MedCard { get; set; }
        public virtual DbSet<Policy> Policy { get; set; }
        public virtual DbSet<Polyclinic> Polyclinic { get; set; }
        public virtual DbSet<ScheduleList> ScheduleList { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<StaffSchedule> StaffSchedule { get; set; }
        public virtual DbSet<StaffType> StaffType { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<VisitHistory> VisitHistory { get; set; }
        public virtual DbSet<WorkDay> WorkDay { get; set; }
        public virtual DbSet<WorkList> WorkList { get; set; }
    }
}
