//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiseaseVisit
    {
        public int DiseaseId { get; set; }
        public int VisitId { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual DiseaseList DiseaseList { get; set; }
        public virtual DiseaseStatus DiseaseStatus { get; set; }
        public virtual VisitHistory VisitHistory { get; set; }
    }
}
