//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkList()
        {
            this.ScheduleList = new HashSet<ScheduleList>();
        }
    
        public int id { get; set; }
        public Nullable<int> idWorkDay { get; set; }
        public Nullable<System.TimeSpan> idWorkStartTme { get; set; }
        public Nullable<System.TimeSpan> idWorkEndTime { get; set; }
        public Nullable<int> ReceptionTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduleList> ScheduleList { get; set; }
        public virtual WorkDay WorkDay { get; set; }
    }
}
