//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.VisitHistory = new HashSet<VisitHistory>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Login { get; set; }
        public string PasswordHash { get; set; }
        public int AccesssLevel { get; set; }
        public string Education { get; set; }
        public int PolyclinicId { get; set; }
        public bool IsMainStaff { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> idScheduleList { get; set; }
        public int Cabinet { get; set; }
    
        public virtual Polyclinic Polyclinic { get; set; }
        public virtual ScheduleList ScheduleList { get; set; }
        public virtual StaffType StaffType { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitHistory> VisitHistory { get; set; }
    }
}
